#Q1

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

#Q2

In [5]:
#to print the data type of variable list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [6]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [7]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#Q3

In [8]:
array_list = np.array(object = list_, dtype = int)

In [9]:
array_list

array([1, 2, 3, 4, 5])

In [11]:
for i in list_:
    print(type(i))  #-->there is no change

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [12]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


#Q4

In [13]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#shape--> prints the dimension of the array
num_array.shape

(2, 3)

In [17]:
#size-->prints the total element present in the array
num_array.size

6

#Q5

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#Q6

In [20]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])